import type { Falla } from './db'

export const SEED_FALLAS: Omit<Falla, 'completitud_pct' | 'created_at' | 'updated_at' | 'synced'>[] = [
  // --- ESPECIAL (3) ---
  {
    id: 'falla-001',
    nombre: "Na Jordana",
    barrio: "El Mercat",
    artista: "Pere Baenas",
    categoria: 'especial',
    lema: "Temps de Joc",
    anyo: 2026,
    lat: 39.4737,
    lng: -0.3780,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
  {
    id: 'falla-002',
    nombre: "Convent Jerusalem",
    barrio: "El Mercat",
    artista: "Santi Morera",
    categoria: 'especial',
    lema: "Paraules al Vent",
    anyo: 2026,
    lat: 39.4722,
    lng: -0.3762,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
  {
    id: 'falla-003',
    nombre: "Pilar - Sagrari",
    barrio: "Campanar",
    artista: "Carlos Carsí",
    categoria: 'especial',
    lema: "L'Enginy Valencià",
    anyo: 2026,
    lat: 39.4764,
    lng: -0.3952,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
  // --- PRIMERA (4) ---
  {
    id: 'falla-004',
    nombre: "Exposicio - Mossen Femades",
    barrio: "Eixample",
    artista: "David Moragues",
    categoria: 'primera',
    lema: "Somnis de Paper",
    anyo: 2026,
    lat: 39.4674,
    lng: -0.3756,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
  {
    id: 'falla-005',
    nombre: "Cuba - Literat Azorin",
    barrio: "Ruzafa",
    artista: "Vicent Martínez",
    categoria: 'primera',
    lema: "La Flama Eterna",
    anyo: 2026,
    lat: 39.4602,
    lng: -0.3713,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
  {
    id: 'falla-006',
    nombre: "Lepant - Guillem de Castro",
    barrio: "Extramurs",
    artista: "Manolo García",
    categoria: 'primera',
    lema: "El Món al Revés",
    anyo: 2026,
    lat: 39.4731,
    lng: -0.3841,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
  {
    id: 'falla-007',
    nombre: "Avinguda Constituicio",
    barrio: "Benimaclet",
    artista: "Trini Castañer",
    categoria: 'primera',
    lema: "Colors de Tardor",
    anyo: 2026,
    lat: 39.4847,
    lng: -0.3624,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
  // --- SEGUNDA (6) ---
  {
    id: 'falla-008',
    nombre: "Palleter - Guillem Sorolla",
    barrio: "Extramurs",
    artista: "Santi Morera",
    categoria: 'segunda',
    lema: "Arrels i Futur",
    anyo: 2026,
    lat: 39.4728,
    lng: -0.3865,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
  {
    id: 'falla-009',
    nombre: "Doctor Serrano - Russafa",
    barrio: "Ruzafa",
    artista: "Pere Baenas",
    categoria: 'segunda',
    lema: "La Llum del Sud",
    anyo: 2026,
    lat: 39.4594,
    lng: -0.3741,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
  {
    id: 'falla-010',
    nombre: "Peris Mencheta - Pinedo",
    barrio: "Quatre Carreres",
    artista: "Carlos Carsí",
    categoria: 'segunda',
    lema: "Tradició Viva",
    anyo: 2026,
    lat: 39.4551,
    lng: -0.3674,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
  {
    id: 'falla-011',
    nombre: "Sant Pau - Trinitat",
    barrio: "L\'Olivereta",
    artista: "David Moragues",
    categoria: 'segunda',
    lema: "Foc i Festa",
    anyo: 2026,
    lat: 39.4668,
    lng: -0.3956,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
  {
    id: 'falla-012',
    nombre: "Mossen Vicent Calvo - Barri",
    barrio: "Patraix",
    artista: "Vicent Martínez",
    categoria: 'segunda',
    lema: "El Tresor Amagat",
    anyo: 2026,
    lat: 39.4624,
    lng: -0.3901,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
  {
    id: 'falla-013',
    nombre: "Ángel Guimerà - Comte",
    barrio: "Jesús",
    artista: "Manolo García",
    categoria: 'segunda',
    lema: "Memòria Col·lectiva",
    anyo: 2026,
    lat: 39.4647,
    lng: -0.3829,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
  // --- TERCERA (7) ---
  {
    id: 'falla-014',
    nombre: "Benimaclet - Escoles",
    barrio: "Benimaclet",
    artista: "Trini Castañer",
    categoria: 'tercera',
    lema: "Joguines de l'Avi",
    anyo: 2026,
    lat: 39.4862,
    lng: -0.3641,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
  {
    id: 'falla-015',
    nombre: "Campanar - Pla de l'Arc",
    barrio: "Campanar",
    artista: "Pere Baenas",
    categoria: 'tercera',
    lema: "El Viatge Impossible",
    anyo: 2026,
    lat: 39.4791,
    lng: -0.3978,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
  {
    id: 'falla-016',
    nombre: "Malilla - Palleter",
    barrio: "Quatre Carreres",
    artista: "Carlos Carsí",
    categoria: 'tercera',
    lema: "Cent Anys de Llum",
    anyo: 2026,
    lat: 39.4523,
    lng: -0.3701,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
  {
    id: 'falla-017',
    nombre: "Padre Porta - Alcasser",
    barrio: "Patraix",
    artista: "Santi Morera",
    categoria: 'tercera',
    lema: "La Barraca del Temps",
    anyo: 2026,
    lat: 39.4607,
    lng: -0.3934,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
  {
    id: 'falla-018',
    nombre: "Jesus - Sant Blai",
    barrio: "Jesús",
    artista: "David Moragues",
    categoria: 'tercera',
    lema: "Dones de Foc",
    anyo: 2026,
    lat: 39.4631,
    lng: -0.3856,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
  {
    id: 'falla-019',
    nombre: "L'Olivereta - Grau",
    barrio: "L\'Olivereta",
    artista: "Vicent Martínez",
    categoria: 'tercera',
    lema: "Sabors de Tardor",
    anyo: 2026,
    lat: 39.4659,
    lng: -0.3985,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
  {
    id: 'falla-020',
    nombre: "Marques de Sotelo - Barcelonina",
    barrio: "El Mercat",
    artista: "Manolo García",
    categoria: 'tercera',
    lema: "Valencia Eterna",
    anyo: 2026,
    lat: 39.4712,
    lng: -0.3799,
    estado: 'pendiente',
    notas: undefined,
    ocr_realizado: false,
  },
]
